export const urlMain = "https://trachanhbuipho.000webhostapp.com/"
// export const urlMain = "localhost:3000"
export const urlDB = "https://trachanhbuipho.000webhostapp.com/"
export const urlImg = "https://trachanhbuipho.000webhostapp.com/img/"
export const widthNav = "250px"